# Generated by Django 5.1.4 on 2024-12-05 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlistitemlink",
            name="wishlist_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wishlist.wishlistitem"
            ),
        ),
    ]
